### ISSUE TITLE
Definir stack

### ISSUE THREAD

**Issue by 0xkalvin** [0xkalvin/fortunator#1]
Precisamos definir as tecnologias que iremos utilizar no front-end e back-end

**Comment by 0xkalvin** [comment]
## Front-end
- React 
- Angular
- Vue 

## Back-end
- Java
- Node


## Infra
### Banco de dados
- Mongo
- Postgres
- SQL server

###  CI/CD
- travis
- jenkins
- github actions
- circle ci


### Hospedagem
- EC2
- heroku
- Hostgateway
- ECS

**Comment by 0xkalvin** [comment]
Node

**Comment by wendelduarte** [comment]
Javão.

**Comment by joaozerwes** [comment]
Node, perdão aos demais

**Comment by Rothero** [comment]
Java

**Comment by KaiqueJuvencio** [comment]
Java

**Comment by 0xkalvin** [comment]
## Front-end

Iremos seguir com **React**

## Back-end
Iremos seguir com **Java**  :angry: 

## Infra

### Banco de dados

Iremos seguir com **Postgres**

### CI/CD
Iremos avaliar as opções acima, de acordo com o preço e facilidade.

### Hospedagem
Iremos avaliar as opções acima, de acordo com o preço e facilidade.

**Comment by 0xkalvin** [comment]
## Hospedagem

Inicialmente, iremos fazer o deploy no heroku
